### ISSUE TITLE
heap_profile fails to parse some stacks

### ISSUE THREAD

**Issue by epickrram** [epickrram/grav#4]
Failed to decode stack: [u'start_thread', u'java_start', u'JavaThread::run', u'JavaThread::thread_main_inner', u'thread_entry', u'JavaCalls::call_
virtual', u'JavaCalls::call_virtual', u'JavaCalls::call_helper', u'call_stub', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'I
nterpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'com/codahale/metrics/WeightedSnapshot:::<init>', u'dtrace_object_al
loc Runtime1 stub', u'SharedRuntime::dtrace_object_alloc']
Failed to decode stack: [u'start_thread', u'java_start', u'JavaThread::run', u'JavaThread::thread_main_inner', u'thread_entry', u'JavaCalls::call_
virtual', u'JavaCalls::call_virtual', u'JavaCalls::call_helper', u'call_stub', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'I
nterpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'com/codahale/metrics/CsvReporter:::reportGauge', u'Interpreter', u'
Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'Java_java_net_Inet6AddressImpl_loo
kupAllHostAddr', u'jni_NewObjectArray', u'ObjArrayKlass::allocate', u'SharedRuntime::dtrace_object_alloc']
Failed to decode stack: [u'start_thread', u'java_start', u'JavaThread::run', u'JavaThread::thread_main_inner', u'thread_entry', u'JavaCalls::call_
virtual', u'JavaCalls::call_virtual', u'JavaCalls::call_helper', u'call_stub', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'I
nterpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'java/util/TreeMap:::entrySet', u'dtrace_object_alloc Runtime1 stub'
, u'SharedRuntime::dtrace_object_alloc']
Failed to decode stack: [u'start_thread', u'java_start', u'JavaThread::run', u'JavaThread::thread_main_inner', u'thread_entry', u'JavaCalls::call_
virtual', u'JavaCalls::call_virtual', u'JavaCalls::call_helper', u'call_stub', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'I
nterpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'Interpreter', u'com/codahale/metrics/MetricRegistry:::getMetrics', u'dtrace_object_
alloc Runtime1 stub', u'SharedRuntime::dtrace_object_alloc']

**Comment by langera** [comment]
fixed. 
k.name sometimes had a non-ascii character which is now stripped.
